[package]
name = "pyarti"
version = "0.0.2"
edition = "2018"

[lib]
name = "pyarti"

crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17.1", features = ["extension-module"] }
arti = { version = "1.0.0", features = ["experimental-api"] }